spring: 
	profiles: 
		active: 
		- dev
---
spring: 
	profiles: test	#
	application: 
		name: microservicecloud-config-zoro-dev
---
spring: 
	profiles: test	#
	application: 
		name: microservicecloud-config-zoro-test